### ISSUE TITLE
Extension signing required as of Firefox 43

### ISSUE THREAD

**Issue by axeleroy** [Rudloff/emoji-everywhere#2]
Hello !

First off, thanks for your development on this extension.

I write this issue to warn you that, as of Firefox 43, extensions are required to be signed in order to be installed. 

Actually, Firefox won't let users install the extension from addons.mozilla.org and for now the only way to bypass this is to disable signature enforcement and install from the XPI available here.

But, in Firefox 48 ([coming out August 2nd](https://wiki.mozilla.org/RapidRelease/Calendar)), signature enforcement won't be overridable.

[Source and documentation](https://wiki.mozilla.org/Addons/Extension_Signing#Timeline)

**Comment by joedf** [comment]
poop ff48...

**Comment by Rudloff** [comment]
Hello,

I'm not sure what your problem is here. The version AMO should already be signed: https://addons.mozilla.org/fr/firefox/addon/emoji-everywhere/

**Comment by axeleroy** [comment]
Oh, then I don't understand why I get the following error when I try to install the extension from addons.mozilla.org

> "The addon could not be installed because it does not match the add-on Firefox expected."

**Comment by Rudloff** [comment]
This seems to be a checksum problem:

```
1465217126536   addons.xpi  WARN    Download of https://addons.mozilla.org/firefox/downloads/file/381188/emoji_everywhere-0.1.1-fx.xpi?src=dp-btn-primary failed: Downloaded file hash (ba034d5d93e0377faf2ff393550c0b0c873796a1b1f4f78d428044801ce3f94e) did not match provided hash (240e06bf24fe94a17123d47235d10b7f9473089e5d1f705e84816f83507cefd6)
```

I think it is not related to extension signing because I can reproduce in Firefox 38.

I reported the bug to Mozilla: https://github.com/mozilla/addons/issues/134

**Comment by Rudloff** [comment]
I have published a new version on AMO.
@axeleroy Can you see if you can install it?

**Comment by axeleroy** [comment]
It works fine now!
