### ISSUE TITLE
Some Emojis not rendered, show as numeric block.

### ISSUE THREAD

**Issue by MarkRH** [Rudloff/emoji-everywhere#4]
Currently using Firefox 47.0.1 in Windows 7 Pro 64bit.  This add-on does show many emojis; however, I have stumbled on a number it doesn't render.  One is this crab emoji (also a high voltage emoji that does work:

This is a crab: 🦀
This is a lighting bolt: ⚡️

Here's a screen shot: http://i.imgur.com/AgjhlYz.png

I picked the crab from here: http://emojikeyboard.org/

Anyway, is there a method for getting these to show that display as a number block?

Thanks,

**Comment by Rudloff** [comment]
Hello,

We use the [Twemoji](https://github.com/twitter/twemoji) icons and the crab one does not seem to be available yet.

**Comment by MarkRH** [comment]
Actually, it doesn't render of these 72 emojis: http://emojipedia.org/unicode-9.0/  

Hmmm

**Comment by MarkRH** [comment]
Looks like version 2 of Twemoji has this one. I guess this add-on is using version 1 still perhaps? https://github.com/twitter/twemoji/issues/159

**Comment by Rudloff** [comment]
Sorry, I thought we were already using Twemoji 2.
I published a new release that uses version 2: https://github.com/Rudloff/emoji-everywhere/releases/tag/0.1.3
(Unicode 9.0 is still missing though.)

**Comment by MarkRH** [comment]
OK, that fixes a lot of them, such as the crab. I wonder why the Unicode 9 ones aren't working? They have one of the images here: https://github.com/twitter/twemoji/blob/gh-pages/2/72x72/1f923.png which is that Rolling On The Floor Laughing one.  

Maybe their other code hasn't been updated yet to use them?  Does look like the image was added 3 days ago.  Looking here it seems their scripts have been updated: https://github.com/twitter/twemoji/tree/gh-pages/2.

Well, I tried out their https://github.com/twitter/twemoji/blob/gh-pages/2/twemoji.min.js file in place of yours and the Unicode 9.0 ones began to render. (I've modified add-ons in the past so I know how to tinker with them).  So, you might try using this one now.

**Comment by Rudloff** [comment]
Yes, I'm still using Twemoji 2.0.5 and Unicode 9 was added in Twemoji 2.1 which was released yesterday.
I will release an update with Twemoji 2.1 but I want to run some tests first.

**Comment by MarkRH** [comment]
OK Cool. Will wait. :)

**Comment by michalpawl** [comment]
I'll be waiting too.

**Comment by Rudloff** [comment]
I tried updating to 2.1.5 but they made some breaking changes to the Bower package: https://github.com/twitter/twemoji/issues/171

**Comment by Rudloff** [comment]
I uploaded a new version based on Twemoji 2.1.6: https://github.com/Rudloff/emoji-everywhere/releases/tag/0.1.4-beta
It should contain the Unicode 9 emojis.

**Comment by michalpawl** [comment]
It looks like I'm going to have to wait until Mozilla approves it :/
https://wiki.mozilla.org/Add-ons/Extension_Signing#Timeline

**Comment by Rudloff** [comment]
You can temporarily set `xpinstall.signatures.required` to `true` in `about:config.`

**Comment by michalpawl** [comment]
![screenshot150](https://cloud.githubusercontent.com/assets/18534393/18256400/46c6a528-73b5-11e6-86b7-dfff4ae2f519.png)
I still couldn't install it even after restarting the browser.

**Comment by Rudloff** [comment]
Sorry, I didn't see that Firefox does not allow that anymore. I will submit a new version for review after #5 is fixed.

**Comment by michalpawl** [comment]
That would be great. Thanks!
